options:
  max_fps: 20
  show_ip: Yes
  num_items_per_row: 5
  fullscreen: Yes
  resolution: "0,0"
  item_height: 220
  padding: 10
  selection_size: 11
  header_height: 140
  disabled_alpha: 128
  background_color: "200,200,200"
  selection_color: "74,239,76"
  text_color: "0,0,0"
  text_highlight_color: "255,255,255"
  item_color: "255,255,255"
  header_color: "255,255,255"
  rom_dot_color: "228,56,65"
  icon_pack_path: "icons/default/"
  font_size: 19
  font_file: "assets/fonts/Lato-Bold.ttf"
  sort_items_alphanum: No
  sort_items_with_roms_first: Yes
  hide_items_without_roms: No
menu_items:
  - label: SNES
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/snes/
    full_path: yes
    command: ~/emulators/pisnes/snes9x  %rom

  - label: MAME4All
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/mame
    full_path: no
    command: mame4all %rom

  - label: AdvMAME
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/mame
    full_path: no
    command: advmame %rom

  - label: Genesis
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/genesis/
    full_path: no
    command: ~/emulators/dgen/dgen %rom

  - label: NES
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/nes/
    full_path: no
    command: ~/emulators/nes/fceux %rom

  - label: Turbographix-16
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/tg16/
    full_path: no
    command: ifconfig

  - label: Atari 2600
    visible: Yes
    icon_file: snes.jpg
    roms: ~/roms/2600/
    full_path: no
    command: stella %rom
