options:
  max_fps: 60
  show_ip: True
  show_update: Yes
  fullscreen: Yes
  resolution: "0,0"
  sort_items_alphanum: True
  sort_items_with_roms_first: True
  hide_items_without_roms: False
  show_cursor: No
  allow_quit_to_console: True
  use_scene_transitions: True
  theme_pack: "default"

scraper_options:
  show_clones: no
  overwrite_images: no

menu_items:
  - label: SNES
    visible: Yes
    roms: /home/pi/pimame/roms/snes/
    full_path: yes
    extension: yes
    override_menu: no
    command: /home/pi/pimame/emulators/pisnes/snes9x

  - label: MAME4All
    visible: No
    roms: /home/pi/pimame/roms/mame4all/
    full_path: no
    override_menu: no
    command: /home/pi/pimame/emulators/mame4all-pi/mame 

  - label: Neo Geo
    visible: Yes
    roms: /home/pi/pimame/roms/neogeo/
    full_path: yes
    extension: yes
    command: /home/pi/pimame/emulators/fba/fba2x

  - label: AdvMAME
    visible: No
    roms: /home/pi/pimame/roms/advmame/
    full_path: no
    command: advmame 

  - label: Final Burn
    visible: Yes
    roms: /home/pi/pimame/roms/pifba/
    full_path: yes
    extension: yes
    override_menu: no
    command: /home/pi/pimame/emulators/fba/fba2x

  - label: Genesis
    visible: Yes
    roms: /home/pi/pimame/roms/genesis/
    full_path: yes
    extension: yes
    command: /home/pi/pimame/emulators/dgen-sdl-1.32/dgen

  - label: NES
    visible: Yes
    roms: /home/pi/pimame/roms/nes/
    full_path: yes
    extension: yes
    command: /home/pi/pimame/emulators/fceux

  - label: Atari 2600
    visible: Yes
    full_path: no
    command: stella
    roms: /home/pi/pimame/roms/2600/
    override_menu: yes

  - label: Playstation 1
    visible: Yes
    full_path: no
    command: /home/pi/pimame/emulators/pcsx_rearmed/pcsx
    override_menu: yes
    roms: /home/pi/pimame/roms/psx/

  - label: Commodore 64
    visible: Yes
    roms: /home/pi/roms/c64/
    full_path: no
    override_menu: yes
    command: x64

  - label: ScummVM
    visible: Yes
    full_path: no
    command: scummvm
    override_menu: yes
    roms: /home/pi/pimame/roms/scummvm/

  - label: Gameboy
    visible: Yes
    roms: /home/pi/pimame/roms/gb/
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen

  - label: Gameboy Advance
    visible: Yes
    full_path: no
    command: /home/pi/pimame/emulators/gpsp/gpsp
    override_menu: yes
    roms: /home/pi/pimame/roms/gba/

  - label: TurboGrafx 16
    visible: Yes
    roms: /home/pi/pimame/roms/tg16
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen -force_module pce_fast

  - label: Controller Setup
    visible: Yes
    full_path: no
    command: python /home/pi/pimame/controller-setup/configure.py
    override_menu: yes

  - label: Cave Story
    visible: Yes
    full_path: no
    command: /home/pi/pimame/emulators/cavestory_rpi-master/nxengine
    override_menu: yes

  - label: Restart
    visible: Yes
    full_path: no
    command: sudo reboot
    override_menu: yes

  - label: Shutdown
    visible: Yes
    full_path: no
    command: sudo poweroff
    override_menu: yes

  - label: Update PiMAME
    visible: Yes
    full_path: no
    command: wget -O - http://pimame.org/update.sh | bash
    override_menu: yes

  - label: Rom Scraper
    visible: Yes
    full_path: no
    command: python /home/pi/pimame/pimame-menu/scraper/scrape_script.py
    override_menu: yes

  - label: Install MAME
    visible: Yes
    full_path: no
    command: python /home/pi/pimame/mame_install.py
    override_menu: yes
