options:
  max_fps: 20
  show_ip: Yes
  num_items_per_row: 5
  fullscreen: Yes
  resolution: "0,0"
  item_height: 220
  padding: 10
  selection_size: 11
  header_height: 140
  disabled_alpha: 128
  background_color: "200,200,200"
  selection_color: "74,239,76"
  text_color: "0,0,0"
  text_highlight_color: "255,255,255"
  item_color: "255,255,255"
  header_color: "255,255,255"
  rom_dot_color: "228,56,65"
  icon_pack_path: "icons/default/"
  font_size: 19
  font_file: "assets/fonts/Lato-Bold.ttf"
  sort_items_alphanum: No
  sort_items_with_roms_first: Yes
  hide_items_without_roms: No
menu_items:
  - label: SNES
    visible: Yes
    icon_file: snes.jpg
    roms: /home/pi/roms/snes/
    full_path: yes
    command: /home/pi/emulators/pisnes/snes9x

  - label: MAME4All
    visible: Yes
    icon_file: mame4all.jpg
    roms: /home/pi/roms/mame
    full_path: no
    command: mame4all

  - label: AdvMAME
    visible: Yes
    icon_file: advmame.jpg
    roms: /home/pi/roms/mame
    full_path: no
    command: advmame

  - label: Genesis
    visible: Yes
    icon_file: genesis.jpg
    roms: /home/pi/roms/genesis/
    full_path: no
    command: /home/pi/emulators/dgen/dgen

  - label: NES
    visible: Yes
    icon_file: nes.jpg
    roms: /home/pi/roms/nes/
    full_path: no
    command: /home/pi/emulators/nes/fceux

  - label: Turbographix-16
    visible: Yes
    icon_file: tg16.jpg
    roms: /home/pi/roms/tg16/
    full_path: no
    command: ifconfig

  - label: Atari 2600
    visible: Yes
    icon_file: 2600.jpg
    roms: /home/pi/roms/2600/
    full_path: no
    command: stella

  - label: Playstation 1
    visible: Yes
    icon_file: psx.jpg
    roms: /home/pi/roms/psx/
    full_path: no
    command: /home/pi/emulators/psx/psx

  - label: Commodore 64
    visible: Yes
    icon_file: c64.jpg
    roms: /home/pi/roms/c64/
    full_path: no
    command: /home/pi/emulators/vice/vice


  - label: ScummVM
    visible: Yes
    icon_file: scummvm.jpg
    roms: /home/pi/roms/scummvm/
    full_path: no
    command: /home/pi/emulators/scummvm/scummvm
    
  - label: Gameboy
    visible: Yes
    icon_file: gameboy.jpg
    roms: /home/pi/roms/gameboy/
    full_path: no
    command: /home/pi/emulators/gameboy/gameboy
    
  - label: Gameboy Advance
    visible: Yes
    icon_file: gba.jpg
    roms: /home/pi/roms/gba/
    full_path: no
    command: /home/pi/emulators/gba/gba
