options:
  max_fps: 20
  show_ip: Yes
  num_items_per_row: 4
  fullscreen: No
  resolution: "800,600"
  item_height: 100
  padding: 10
  selection_size: 11
  header_height: 140
  disabled_alpha: 128
  background_color: "200,200,200"
  selection_color: "74,239,76"
  text_color: "0,0,0"
  text_highlight_color: "255,255,255"
  item_color: "255,255,255"
  header_color: "255,255,255"
  rom_dot_color: "228,56,65"
  icon_pack_path: "icons/default/"
  font_size: 19
  font_file: "assets/fonts/Lato-Bold.ttf"
  sort_items_alphanum: No
  sort_items_with_roms_first: Yes
  hide_items_without_roms: No
menu_items:
  - label: SNES
    visible: Yes
    icon_file: snes.jpg
    roms: roms/snes/
    command: echo snes #/home/emulators/dgen/dgen %rom

  - label: Genesis
    visible: Yes
    icon_file: snes.jpg
    roms: roms/genesis/
    command: ifconfig #/home/emulators/dgen/dgen %rom

  - label: NES
    visible: Yes
    icon_file: snes.jpg
    roms: roms/nes/
    command: echo nes #/home/emulators/dgen/dgen %rom

  - label: Turbographix-16
    visible: Yes
    icon_file: snes.jpg
    roms: roms/tg16/
    command: ifconfig #/home/emulators/dgen/dgen %rom

  - label: Atari 2600
    visible: Yes
    icon_file: snes.jpg
    roms: roms/2600/
    command: ifconfig #/home/emulators/dgen/dgen %rom